@urlBase = http://localhost:8000


### API HEALTH
GET {{urlBase}}/api/health?locale=es-ES
Accept-Language: es-ES,es;q=0.9,en;q=0.8

### ADMIN HEALTH (IN BROWSER)
GET {{urlBase}}/admin/health


### OPENAPI DOCS (IN BROWSER)
GET {{urlBase}}/docs

### OPENAPI REDOCS (IN BROWSER)
GET {{urlBase}}/redoc
