@urlBase = http://localhost:8000/api/core
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtbWFuZXoiLCJleHAiOjE3MjQxNTcwODV9.nWsVHEWFTolwnTjVXisI2AHLD7mvFs5dr5fuFMD-uFk

####################################################### GROUP ##########################################################

### GROUP - CREATE
POST {{urlBase}}/groups?locale=es_ES

{
    "code": "ai",
    "webname": "ainia"
}

### GROUP - READ BY ID
GET {{urlBase}}/groups/d8405ea8-3c7e-4b82-abb6-7f6c2445c1f0?locale=es_ES

### GROUP - READ INDEX
GET {{urlBase}}/groups/index
Authorization: Bearer {{token}}

### GROUP - READ PAGINATED
GET {{urlBase}}/groups?page=1&size=10&direction=asc&order_field=code&target=ainia

### GROUP - UPDATE
PUT {{urlBase}}/groups/c998846c-3ee7-435c-9910-fb9b0b5ee372

{
    "code": "ainia",
    "webname": "ainia",
    "active": "true"
}

### GROUP - DELETE BY ID
DELETE {{urlBase}}/groups/419390fd-e26a-461f-80b1-1154ec65a93e

### GROUP - UPDATE MODULES
PATCH {{urlBase}}/groups/59af182f-0bee-43b9-9f6c-d325691950e2/modules

[ "08100acc-9cbe-4263-b8b3-294976c288c3", "16b6ab5a-a588-4a68-9450-b118c75afa9a" ]

####################################################### ROLE ###########################################################

### ROLE - CREATE
POST {{urlBase}}/roles

{
    "code": "role3",
    "webname": "role 3"
}

### ROLE - READ BY ID
GET {{urlBase}}/roles/d3bc9238-ca0a-47e7-adfd-f2dcb541e5e6

### ROLE - READ INDEX
GET {{urlBase}}/roles/index

### ROLE - READ PAGINATED
GET {{urlBase}}/roles?page=1&size=10&direction=asc&order_field=code&target=admin

### ROLE - UPDATE
PUT {{urlBase}}/roles/375fdcab-4027-427d-9e1c-37eb3985cd6f

{
    "code": "user",
    "webname": "user"
}

### ROLE - DELETE BY ID
DELETE {{urlBase}}/roles/d3bc9238-ca0a-47e7-adfd-f2dcb541e5e6

####################################################### USER ###########################################################

### USER - CREATE
POST {{urlBase}}/users

{
    "username": "otro8",
    "password_raw": "secret",
    "firstname": "otro1",
    "lastname": "Máñez Ramón",
    "group_id": "59af182f-0bee-43b9-9f6c-d325691950e2",
    "role_id": "d3bc9238-ca0a-47e7-adfd-f2dcb541e5e6"
}

### USER - READ BY ID
GET {{urlBase}}/users/4f7dfe00-dc48-4a95-8336-04510f2568ba

### USER - READ INDEX
GET {{urlBase}}/users/index

### USER - READ PAGINATED
GET {{urlBase}}/users?page=1&size=10&direction=asc&order_field=username&active=False

### USER - UPDATE
PUT {{urlBase}}/users/784874f7-7abf-431e-a85a-1dfd8096913a

{
    "username": "otro8",
    "password_raw": "secret",
    "firstname": "otro2",
    "lastname": "Otro2 otro3",
    "active": true,
    "is_god": true,
    "group_id": null,
    "role_id": "d3bc9238-ca0a-47e7-adfd-f2dcb541e5e"
}

### USER - DELETE BY ID
DELETE {{urlBase}}/users/5047454c-3e8f-41af-af3d-27cac9ea8123

####################################################### MODULE #########################################################

### MODULE - CREATE
POST {{urlBase}}/modules?locale=en_US

{
    "code": "MODULE1",
    "webname": "module 1"
}

### MODULE - READ BY ID
GET {{urlBase}}/modules/08100acc-9cbe-4263-b8b3-294976c288c3

### MODULE - READ INDEX
GET {{urlBase}}/modules/index

### MODULE - READ PAGINATED
GET {{urlBase}}/modules?page=1&size=10&direction=asc&order_field=code&target=mod

### MODULE - UPDATE
PUT {{urlBase}}/modules/5ce115a4-a923-4af7-855b-f8efad8a1015

{
    "code": "MODULE",
    "webname": "module"
}

### MODULE - DELETE BY ID
DELETE {{urlBase}}/modules/5ce115a4-a923-4af7-855b-f8efad8a1015


####################################################### RESOURCE #######################################################


### MODULE RESOURCE - CREATE
POST {{urlBase}}/modules/08100acc-9cbe-4263-b8b3-294976c288c3/resources?locale=es_ES

{
    "code": "MO"
}


### MODULE RESOURCE - READ INDEX
GET {{urlBase}}/modules/ed6fe0a4-0f73-48cb-a0db-70db6722e80d/resources/index


### MODULE RESOURCE - READ BY ID
GET {{urlBase}}/resources/7455c736-8866-4a32-aa91-b3bdbbb51b94


### MODULE RESOURCE - UPDATE
PUT {{urlBase}}/resources/7455c736-8866-4a32-aa91-b3bdbbb51b94

{
    "code": "MODULE2RESOURCE2NEW",
    "module_id": "08100acc-9cbe-4263-b8b3-294976c288c3"
}


### MODULE RESOURCE - DELETE BY ID
DELETE {{urlBase}}/resources/7455c736-8866-4a32-aa91-b3bdbbb51b94


##################################################### PERMISSION #######################################################


### ROLE PERMISSION - CREATE
POST {{urlBase}}/roles/375fdcab-4027-427d-9e1c-37eb3985cd6f/permissions

{
    "scope": "CRUD",
    "scope_owner": "R",
    "resource_id": "d886d27f-4d07-48b2-93ba-e025946f9786"
}


### ROLE PERMISSION - READ INDEX FILTERED
GET {{urlBase}}/roles/375fdcab-4027-427d-9e1c-37eb3985cd6f/permissions/index?module_id=ed6fe0a4-0f73-48cb-a0db-70db6722e80d


### ROLE PERMISSION - READ BY ID
GET {{urlBase}}/permissions/555d6151-cb75-4123-92bf-3aeb51ccc124


### ROLE PERMISSION - UPDATE
PUT {{urlBase}}/permissions/de86655e-e007-41e7-9251-6616386b9b86

{
    "scope": "R",
    "scope_owner": "CRUD"
}

### ROLE PERMISSION - DELETE BY ID
DELETE {{urlBase}}/permissions/88910f3d-b2b4-404f-9028-dd4f4a1caa84


####################################################### MENU ###########################################################


### MENU - CREATE
POST {{urlBase}}/menus

{
    "code": "menu 12",
    "link": "link 12",
    "parent_id": "06961cae-4b81-4db2-abd0-47f6f3587880",
    "module_id": "ed6fe0a4-0f73-48cb-a0db-70db6722e80d"
}

### MENU - TREE
GET {{urlBase}}/menus/tree

### MENU - READ BY ID
GET {{urlBase}}/menus/e0d761d9-98a9-4f63-a1ad-ef7124e4af14

### MENU - UPDATE
PUT {{urlBase}}/menus/e0d761d9-98a9-4f63-a1ad-ef7124e4af14

{
    "code": "menu 11 updated",
    "link": "link 11 updated",
    "parent_id": "06961cae-4b81-4db2-abd0-47f6f3587880",
    "module_id": "ed6fe0a4-0f73-48cb-a0db-70db6722e80d"
}

### MENU - DELETE
DELETE {{urlBase}}/menus/e0d761d9-98a9-4f63-a1ad-ef7124e4af14

### ROLE - UPDATE MENUS
PATCH {{urlBase}}/roles/375fdcab-4027-427d-9e1c-37eb3985cd6f/menus

[ "06961cae-4b81-4db2-abd0-47f6f3587880", "1990098d-054c-4f66-9636-a04aff773bec", "b27be874-366a-4432-9276-2707d2ba89ec" ]

### ROLE - MENUS TREE
GET {{urlBase}}/roles/375fdcab-4027-427d-9e1c-37eb3985cd6f/menus/tree


#################################################### CONFIGURATION #####################################################

### CONFIGURATION - CREATE
POST {{urlBase}}/configurations

{
    "code": "config 1",
    "module_id": "ed6fe0a4-0f73-48cb-a0db-70db6722e80d"
}

### CONFIGURATION - READ BY ID
GET {{urlBase}}/configurations/b4547f98-dc18-48a5-9ea6-dccdb54693b6

### CONFIGURATION - READ INDEX
GET {{urlBase}}/configurations/index

### CONFIGURATION - UPDATE 
PUT {{urlBase}}/configurations/b4547f98-dc18-48a5-9ea6-dccdb54693b6

{
    "code": "config 1 updated",
    "module_id": "ed6fe0a4-0f73-48cb-a0db-70db6722e80d"
}

### CONFIGURATION - DELETE BY ID
DELETE {{urlBase}}/configurations/ca4c56de-3f71-4ec3-860d-888718ac6f37


################################################ CONFIGURATION VAUES ###################################################

### GROUP CONFIGURATION VALUE - CREATE

POST {{urlBase}}/groups/59af182f-0bee-43b9-9f6c-d325691950e2/configuration-values

{
    "configuration_id": "b4547f98-dc18-48a5-9ea6-dccdb54693b6",
    "value": "value 1"
}

### GROUP CONFIGURATION VALUE - READ INDEX
GET {{urlBase}}/groups/59af182f-0bee-43b9-9f6c-d325691950e2/configuration-values/index

### GROUP CONFIGURATION VALUE - READ BY ID #####
GET {{urlBase}}/configuration-values/59af182f-0bee-43b9-9f6c-d325691950e2

### GROUP CONFIGURATION VALUE - UPDATE ####
PUT {{urlBase}}/configuration-values/59af182f-0bee-43b9-9f6c-d325691950e2

{
    "value": "value 1 updated"
}

### GROUP CONFIGURATION VALUE - DELETE BY ID ####
DELETE {{urlBase}}/configuration-values/59af182f-0bee-43b9-9f6c-d325691950e2



####################################################### AUTH ###########################################################


POST {{urlBase}}/auth?locale=es_ES
Content-Type: application/x-www-form-urlencoded

username=mmanez
&password=secret