@urlBase = http://localhost:8000/api/core


### GROUP - CREATE
POST {{urlBase}}/groups

{
    "code": "ainia1",
    "webname": "ainia1"
}

### GROUP - READ BY ID
GET {{urlBase}}/groups/b6c2e786-650d-46fb-a593-c6f53a680b9d

### GROUP - READ INDEX
GET {{urlBase}}/groups/index

### GROUP - READ PAGINATED
GET {{urlBase}}/groups?page=1&size=1&direction=asc&order_field=code