version: '3.8'

services:
  app:
    container_name: fastapi_saas_dev_local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      # - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
